const actions = {
  USER_LOGIN: 'USER_LOGIN',
  ADD_EXPENSES: 'ADD_EXPENSES',
  EDIT_EXPENSES: 'EDIT_EXPENSES',
  DELETE_EXPENSE: 'DELETE_EXPENSE',
  REQUEST_CURRENCIES: 'REQUEST_CURRENCIES',
  WALLET_CURRENCIES: 'WALLET_CURRENCIES',
  FAILED_CURRENCIES: 'FAILED_CURRENCIES',
  ADD_ACCOUNT: 'ADD_ACCOUNT',
};

export default actions;
